# Generated by Django 5.2.1 on 2025-06-13 14:26

import django.db.models.deletion
import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordre_affichage', 'titre'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='disponible',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='service',
            name='specifications_techniques',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unite_mesure',
        ),
        migrations.AddField(
            model_name='service',
            name='id_categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web_site.categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ordre_affichage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RenameModel(
            old_name='ServiceDetail',
            new_name='Service_ModelDetail',
        ),
        migrations.CreateModel(
            name='Service_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite_mesure', models.CharField(help_text='A4, A3, m², pièce, etc.', max_length=50)),
                ('specifications_techniques', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_site.models.upload_service_image)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_models', to='web_site.service')),
            ],
            options={
                'verbose_name': 'Service model',
                'verbose_name_plural': 'Services models',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='service_modeldetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service_modeldetail',
            name='service_model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='web_site.service_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandeitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.service_model'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='services_utilises',
            field=models.ManyToManyField(blank=True, related_name='realisations', to='web_site.service_model'),
        ),
        migrations.AlterUniqueTogether(
            name='service_modeldetail',
            unique_together={('service_model', 'nom_option')},
        ),
        migrations.RemoveField(
            model_name='service_modeldetail',
            name='service',
        ),
    ]
