# Generated by Django 5.2.1 on 2025-06-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_model',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.service'),
        ),
    ]
