# Generated by Django 5.2.1 on 2025-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_service_model_id_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web_site/static/categories/'),
        ),
    ]
