# Generated by Django 5.2.1 on 2025-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_alter_categorie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/categories/'),
        ),
    ]
