# Generated by Django 5.2.1 on 2025-06-14 19:15

import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_alter_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=web_site.models.upload_service_image),
        ),
    ]
